name: ci

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
          id-token: write
          contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0

      - name: Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - uses: eLco/setup-terragrunt@v1.0.2
        with:
          terragrunt_version: 0.43.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: eu-west-2

      - name: Plan
        run: make ENV=ci plan-in-container
